argentlabs/argent-contracts-starknet

- .gitignore
- README.md
- requirements.txt
- test/utils/TransactionBuilder.py
- test/utils/deploy.py
- Move Python dependencies to standard `requirements.txt` file
- Update README
- Fix common Python gotcha with default argument
- Refactor signature concatenations
> Python miscenalleous

- contracts/ArgentAccount.cairo
- test/argent_account.py
Adds a `get_version` view method returning the version as a short string.
Current version is `0.1.0`.
> Add version number

- contracts/ArgentAccount.cairo
- requirements.txt
- test/argent_account.py
Leverage the new `get_contract_address()` system call.
> update to cairo 0.6.0

- contracts/StructHash.cairo
- test/struct_hash.py
> feat: add struct hash

- contracts/ArgentAccount.cairo
- test/argent_account.py
- test/utils/utilities.py
Add error messages to ArgentAccount.
> error message

- contracts/ArgentAccount.cairo
- test/argent_account.py
- test/utils/Signer.py
- test/utils/TransactionSender.py
- test/utils/utilities.py
Some cleaning around multicalls and aligning with OZ.
> Clean after multicall

- contracts/ArgentAccount.cairo
- test/argent_account.py
- test/proxy.py
- test/utils/utilities.py
Add `account_upgrade` and `transaction_executed` events to ArgentAccount.cairo.
> add account_upgrade and transaction_executed events

- test/utils/TransactionSender.py
Hello,
Sorry I'm reopening an issue, TransactionSender.py was missing from your merge
> Removed unused import on test

- contracts/ArgentAccount.cairo
- test/argent_account.py
Companion PR to https://github.com/OpenZeppelin/cairo-contracts/pull/338 . See mentioned PR for more info! :)
> Add return value to is_valid_signature

- contracts/ArgentAccount.cairo
- contracts/Proxy.cairo
- contracts/Upgradable.cairo
- requirements.txt
- scripts/calculate-class-hash.py
- test/proxy.py
- test/utils/utilities.py
> Upgrade to Cairo v0.9.0

- contracts/ArgentAccount.cairo
changed `validate_signer_signature` and `validate_guardian_signature` param order
> Code consistency for list and list_len param order

- pyproject.toml
- requirements.txt
- test/address_registry.py
- test/argent_account.py
And fixed test/address_registry.py
> starknet_version in blockInfo for Cairo 0.9.1

- contracts/account/ArgentAccount.cairo
- contracts/account/ArgentPluginAccount.cairo
- contracts/account/library.cairo
> accept transaction with version = QUERY for simulation

- README.md
Update the Readme instruction to address a few gotchas i faced during installation
> Update setup guide

- contracts/account/ArgentAccount.cairo
- contracts/account/ArgentPluginAccount.cairo
This will apply the suggestions found the previous PR https://github.com/argentlabs/argent-contracts-starknet/pull/64
> Upgrade and call improvements

- test/conftest.py
- test/test_argent_account.py
- test/test_argent_deploy.py
- test/test_argent_plugin_account.py
- test/test_multicall.py
- test/test_proxy.py
- test/test_session_keys.py
- test/test_struct_hash.py
- test/test_universal_deployer.py
- test/utils/Signer.py
- test/utils/TransactionSender.py
- test/utils/utilities.py
Add some tests for self deployment
Includes some changes to cache contract compilation using fixtures to speed up the tests
> Deployment Tests

- contracts/argent_account.cairo
Adds basic supports for ERC165 `supportsInterface` checking and custom interface registering.
> Initial support for ERC165

- contracts/erc20.cairo
- contracts/lib.cairo
Adding the ERC20 file provided by Starkware.
Will later be useful in tests
> Import ERC20 from starkware example

- contracts/argent_account.cairo
- contracts/test_argent_account.cairo
> Add `changeSigner`, `changeGuardian` and `changeGuardianBackup` methods

- Makefile
- Rename INSTALLATION-FOLDER to INSTALLATION_FOLDER
- Changing the contracts folder to a CONST
> Rework makefile to use const

- Cargo.lock
- Cargo.toml
- Makefile
- contracts/erc20.cairo
Updating toml to latest commit of Starkware 
Adding the building of vscode to the makefile
And updating ERC20 to latest
> Update toml and add vscode compile to makefile

- contracts/argent_account.cairo
- contracts/tests/test_argent_account_signatures.cairo
Update the argent_account to deref signature_r and signature_s due to Starkware changes
> Update account to deref signature

- .github/workflows/ci.yml
- Makefile
- contracts/argent_account.cairo
- contracts/lib.cairo
- contracts/tests.cairo
- contracts/tests/test_argent_account_signatures.cairo
Make install will now also build and compile the vscode extension
Also updated argent_account to pass tests due to SW changes
> Adding installation of vscode in install phase
